import type { CardDefinition } from './cardTypes';

export const starterCards: CardDefinition[] = [
  {
    id: 'basic-shot',
    name: 'Обычный выстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'starter',
    cost: 1,
    description: 'Наносит 6 урона выбранному врагу.',
    effects: [{ type: 'damage', amount: 6, target: 'enemy' }],
  },
  {
    id: 'raise-shield',
    name: 'Поднять щит',
    type: 'skill',
    target: 'self',
    rarity: 'starter',
    cost: 1,
    description: 'Даёт 5 брони.',
    effects: [{ type: 'block', amount: 5, target: 'player' }],
  },
  {
    id: 'reload',
    name: 'Перезарядка',
    type: 'skill',
    target: 'self',
    rarity: 'starter',
    cost: 0,
    exhaust: true,
    description: 'Даёт 1 энергию. Расходуется до конца боя.',
    effects: [{ type: 'gainEnergy', amount: 1 }],
  },
  {
    id: 'roll',
    name: 'Перекат',
    type: 'skill',
    target: 'self',
    rarity: 'starter',
    cost: 1,
    description: 'Даёт 5 брони. Возьмите 2 карты.',
    effects: [
      { type: 'block', amount: 5, target: 'player' },
      { type: 'draw', amount: 2 },
    ],
  },
];

export const tatianaRewardCards: CardDefinition[] = [
  {
    id: 'tatiana-card-001',
    name: 'Двойной выстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 1,
    description: '5*2',
    effects: [{ type: 'damage', amount: 10, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-002',
    name: 'Маркирующая граната',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: '+ 3 прицела всем',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 3, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-003',
    name: 'Стойкое пламя',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: '+ 2 хода горения',
    tags: ['burn'],
    effects: [{ type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-004',
    name: 'Тройной выстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 1,
    description: '5*3',
    effects: [{ type: 'damage', amount: 15, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-005',
    name: 'Прицелиться',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    description: '+ 5 прицела',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 5, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-006',
    name: 'Под прицелом',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: 'Прицеливание больше не спадает',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 2, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-007',
    name: 'Выстрел по ногам',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 1,
    description: '5 + слабость',
    tags: ['control'],
    effects: [{ type: 'damage', amount: 5, target: 'enemy' }, { type: 'applyStatus', status: 'weak', amount: 5, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-008',
    name: 'Глухая оборона',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    description: '15 защиты',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 15, target: 'player' }],
  },
  {
    id: 'tatiana-card-009',
    name: 'Разведка',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: '+ 1 карта в ход',
    effects: [{ type: 'draw', amount: 1 }],
  },
  {
    id: 'tatiana-card-010',
    name: 'ЭМИ выстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 2,
    description: '20 урона машине',
    effects: [{ type: 'damage', amount: 20, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-011',
    name: 'Хороший прицел',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: '+ 2 прицела случайному противнику в ход',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 2, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-012',
    name: 'Осколочная граната',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'common',
    cost: 2,
    exhaust: true,
    description: '12 всем',
    effects: [{ type: 'damage', amount: 12, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-013',
    name: 'Усиление щита',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    description: '8 защиты + 5 в след ход',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 8, target: 'player' }],
  },
  {
    id: 'tatiana-card-014',
    name: 'Искусство войны',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: 'В начале хода можно сбросить до двух карт и взять столько же',
    effects: [{ type: 'draw', amount: 1 }],
  },
  {
    id: 'tatiana-card-015',
    name: 'Стрельба от бедра',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'common',
    cost: 1,
    description: '5*n по случайным целям',
    effects: [{ type: 'damage', amount: 5, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-016',
    name: 'Отражающий щит',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    description: '10 защиты + возврат урона',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 10, target: 'player' }],
  },
  {
    id: 'tatiana-card-017',
    name: 'Восстановление щита',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: 'Каждый ход + 4 защиты',
    tags: ['shield'],
    effects: [],
  },
  {
    id: 'tatiana-card-018',
    name: 'Стрельба зажигательными',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 1,
    description: '5(10, если враг горит) + периодический урон 4 + 3 хода',
    tags: ['burn'],
    effects: [{ type: 'damage', amount: 5, target: 'enemy' }, { type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-019',
    name: 'Перегрузка щита',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 2,
    exhaust: true,
    description: '20 Защиты, но след ход без защиты',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 20, target: 'player' }],
  },
  {
    id: 'tatiana-card-020',
    name: 'Усиленная батарея',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: 'Защита не спадает',
    tags: ['shield'],
    effects: [],
  },
  {
    id: 'tatiana-card-021',
    name: 'Молотов',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'common',
    cost: 2,
    exhaust: true,
    description: '3(8, если враг горит) + периодический урон 4 всем + 3 хода',
    tags: ['burn'],
    effects: [{ type: 'damage', amount: 3, target: 'all-enemies' }, { type: 'applyStatus', status: 'burn', amount: 4, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-022',
    name: 'Двухсторонний щит',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    description: '14 защиты, но атаковать нельзя',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 14, target: 'player' }],
  },
  {
    id: 'tatiana-card-023',
    name: 'Усилить смесь',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: '+ 4 урона от горения',
    tags: ['burn'],
    effects: [{ type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-024',
    name: 'ЭМИ граната',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'common',
    cost: 2,
    exhaust: true,
    description: '25 урона машинам всем',
    effects: [{ type: 'damage', amount: 25, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-025',
    name: 'Предусмотрительность',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    description: '+ 2 действия в след ход',
    effects: [{ type: 'gainEnergy', amount: 2 }],
  },
  {
    id: 'tatiana-card-026',
    name: 'Адреналин',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 0,
    exhaust: true,
    description: '+ 1 действие в начале хода',
    effects: [{ type: 'gainEnergy', amount: 1 }],
  },
  {
    id: 'tatiana-card-027',
    name: 'Прицельный выстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 2,
    description: '20 урона',
    tags: ['aim'],
    effects: [{ type: 'damage', amount: 20, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-028',
    name: 'Огненная ловушка',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: '3(8, если враг горит) + периодический урон 4 + 3 хода (если враг атаковал)',
    tags: ['burn'],
    effects: [{ type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-029',
    name: 'Огнемет',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: 'Любая атака имеет шанс в 25% поджечь цель + 3 хода горения',
    tags: ['burn'],
    effects: [{ type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-030',
    name: 'Выстрел наотмаш',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 1,
    description: '4 урона + 5 защиты',
    tags: ['shield'],
    effects: [{ type: 'damage', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-031',
    name: 'Перебинтоваться',
    type: 'skill',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: '+ 4 хп',
    effects: [{ type: 'heal', amount: 4 }],
  },
  {
    id: 'tatiana-card-032',
    name: 'Кучная стрельба',
    type: 'talent',
    target: 'self',
    rarity: 'common',
    cost: 1,
    exhaust: true,
    description: 'Любая атака добавляет + 1 прицела',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 1, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-033',
    name: 'Калечащий выстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'common',
    cost: 1,
    description: '10 урона + слабость 2 хода',
    tags: ['control'],
    effects: [{ type: 'damage', amount: 10, target: 'enemy' }, { type: 'applyStatus', status: 'weak', amount: 10, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-034',
    name: 'Знание поля боя',
    type: 'skill',
    target: 'all-enemies',
    rarity: 'uncommon',
    cost: 1,
    description: '+ 2 прицела всем врагам, + 2 карты',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 2, target: 'all-enemies' }, { type: 'draw', amount: 2 }],
  },
  {
    id: 'tatiana-card-035',
    name: 'Разгорающееся пламя',
    type: 'talent',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    exhaust: true,
    description: 'При воспламенении врага - шанс 25%, поджечь еще одного + 3 хода горения',
    tags: ['burn'],
    effects: [{ type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-036',
    name: 'Выстрел картечью',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'uncommon',
    cost: 2,
    description: '10 урона всем',
    effects: [{ type: 'damage', amount: 10, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-037',
    name: 'Подготовка',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    description: 'следующая атака нанесет двойной урон',
    effects: [],
  },
  {
    id: 'tatiana-card-038',
    name: 'В очередь',
    type: 'talent',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    exhaust: true,
    description: 'Цель с прицелом умирает - все прицелы перекидываются на случайного врага',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 2, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-039',
    name: 'Добивающий выстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '12 урона и добивание, если ХП врага ниже 10% после выстрела',
    effects: [{ type: 'damage', amount: 12, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-040',
    name: 'Многозадачность',
    type: 'talent',
    target: 'self',
    rarity: 'uncommon',
    cost: 0,
    exhaust: true,
    description: '3 атаки или 3 навыка - + 1 действие',
    effects: [{ type: 'gainEnergy', amount: 1 }],
  },
  {
    id: 'tatiana-card-041',
    name: 'Пристреляться',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '5 урона + 2 прицела',
    tags: ['aim'],
    effects: [{ type: 'damage', amount: 5, target: 'enemy' }, { type: 'applyStatus', status: 'aim', amount: 5, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-042',
    name: 'Проверить рюкзак',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 2,
    exhaust: true,
    description: 'Добрать карт до максимума',
    effects: [{ type: 'draw', amount: 5 }],
  },
  {
    id: 'tatiana-card-043',
    name: 'Охота',
    type: 'talent',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    exhaust: true,
    description: 'Обычные живые враги получают + 3 урона от любых атак',
    effects: [],
  },
  {
    id: 'tatiana-card-044',
    name: 'Выстрел на упреждение',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '5 урона + 2 карты',
    effects: [{ type: 'damage', amount: 5, target: 'enemy' }, { type: 'draw', amount: 2 }],
  },
  {
    id: 'tatiana-card-045',
    name: 'Ловкие пальцы',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    description: 'взять в руку карту из сброса',
    effects: [{ type: 'draw', amount: 1 }],
  },
  {
    id: 'tatiana-card-046',
    name: 'Стрельба вслепую',
    type: 'talent',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    exhaust: true,
    description: '1 карта с верха добора разыгрывается бесплатно',
    effects: [{ type: 'draw', amount: 1 }],
  },
  {
    id: 'tatiana-card-047',
    name: 'Снайперский выстрел',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'uncommon',
    cost: 2,
    description: '10 + Постратить все прицелы, за каждый + 3 урона',
    tags: ['aim'],
    effects: [{ type: 'damage', amount: 10, target: 'all-enemies' }, { type: 'applyStatus', status: 'aim', amount: 10, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-048',
    name: 'Снабжение',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    description: 'Вернуть израсходованную карту в руку',
    effects: [],
  },
  {
    id: 'tatiana-card-049',
    name: 'Настоящий профи',
    type: 'talent',
    target: 'self',
    rarity: 'uncommon',
    cost: 0,
    exhaust: true,
    description: 'случайная карта в руке теряет стоимость',
    effects: [],
  },
  {
    id: 'tatiana-card-050',
    name: 'Стрельба на подавление',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'uncommon',
    cost: 2,
    description: '5 урона + слабость 2 хода всем',
    tags: ['control'],
    effects: [{ type: 'damage', amount: 5, target: 'all-enemies' }, { type: 'applyStatus', status: 'weak', amount: 5, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-051',
    name: 'Обыск',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    exhaust: true,
    description: 'После убийства цели + 1 случайный предмет',
    effects: [],
  },
  {
    id: 'tatiana-card-052',
    name: 'Гранатометчик',
    type: 'talent',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    exhaust: true,
    description: 'эффект гранат удваивается',
    effects: [],
  },
  {
    id: 'tatiana-card-053',
    name: 'Удар прикладом',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '4 урона + 1 карта',
    effects: [{ type: 'damage', amount: 4, target: 'enemy' }, { type: 'draw', amount: 1 }],
  },
  {
    id: 'tatiana-card-054',
    name: 'Подсечка',
    type: 'skill',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '+ 2 слабости на врага',
    tags: ['control'],
    effects: [{ type: 'applyStatus', status: 'weak', amount: 2, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-055',
    name: 'Пулеметный шквал',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '3 урона 6 раз случайным врагам',
    effects: [{ type: 'damage', amount: 3, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-056',
    name: 'Огненный щит',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    description: '(5, если враг горит) + периодический урон 4 + 3 хода',
    tags: ['burn'],
    effects: [{ type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-057',
    name: 'Расстрел',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '5*n',
    effects: [{ type: 'damage', amount: 5, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-058',
    name: 'Знание врага',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    description: 'Удвоить негативные эффекты на враге',
    effects: [],
  },
  {
    id: 'tatiana-card-059',
    name: 'Детанирующая пуля',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '8 урона(13, если враг горит) +  периодический урон 4 + 3 хода',
    tags: ['burn'],
    effects: [{ type: 'damage', amount: 8, target: 'enemy' }, { type: 'applyStatus', status: 'burn', amount: 4, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-060',
    name: 'Ослабить',
    type: 'skill',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: 'слабость 1 ход',
    tags: ['control'],
    effects: [{ type: 'applyStatus', status: 'weak', amount: 1, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-061',
    name: 'Выстрел трассирующей пулей',
    type: 'attack',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: '5 + уязвимость 2 хода',
    tags: ['control'],
    effects: [{ type: 'damage', amount: 5, target: 'enemy' }, { type: 'applyStatus', status: 'vulnerable', amount: 5, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-062',
    name: 'Найти уязвимость',
    type: 'skill',
    target: 'enemy',
    rarity: 'uncommon',
    cost: 1,
    description: 'уязвимость 1 ход',
    tags: ['control'],
    effects: [{ type: 'applyStatus', status: 'vulnerable', amount: 1, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-063',
    name: 'Газовая граната',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'uncommon',
    cost: 2,
    exhaust: true,
    description: '5 урона + 3 слабости всем',
    tags: ['control'],
    effects: [{ type: 'damage', amount: 5, target: 'all-enemies' }, { type: 'applyStatus', status: 'weak', amount: 5, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-064',
    name: 'Укрепление',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    description: '8 защиты + 1 карта',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 8, target: 'player' }, { type: 'draw', amount: 1 }],
  },
  {
    id: 'tatiana-card-065',
    name: 'Динамит',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'uncommon',
    cost: 2,
    exhaust: true,
    description: '40 урона всем через 3 хода',
    effects: [{ type: 'damage', amount: 40, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-066',
    name: 'Боевое прошлое',
    type: 'skill',
    target: 'self',
    rarity: 'uncommon',
    cost: 1,
    description: 'найти и взять в руку карту из колоды добора',
    effects: [{ type: 'draw', amount: 1 }],
  },
  {
    id: 'tatiana-card-067',
    name: 'Пылающий залп',
    type: 'attack',
    target: 'all-enemies',
    rarity: 'uncommon',
    cost: 2,
    description: '5(10, если враг горит) + периодический урон 4 + 3 хода всем',
    tags: ['burn'],
    effects: [{ type: 'damage', amount: 5, target: 'all-enemies' }, { type: 'applyStatus', status: 'burn', amount: 4, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-068',
    name: 'Аптечка',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    description: '+ 8 хп',
    effects: [{ type: 'heal', amount: 8 }],
  },
  {
    id: 'tatiana-card-069',
    name: 'Маркирующий выстрел в голову',
    type: 'attack',
    target: 'enemy',
    rarity: 'rare',
    cost: 1,
    description: '10 урона + 2 прицела',
    tags: ['aim'],
    effects: [{ type: 'damage', amount: 10, target: 'enemy' }, { type: 'applyStatus', status: 'aim', amount: 10, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-070',
    name: 'Дубликат батареи',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    description: 'получить столько защиты в след ход сколько у вас сейчас',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 5, target: 'player' }],
  },
  {
    id: 'tatiana-card-071',
    name: 'Выстрел экспансивной пулей',
    type: 'attack',
    target: 'enemy',
    rarity: 'rare',
    cost: 1,
    description: '15 урона + кровотечение 5 урона 4 хода (только по живым)',
    effects: [{ type: 'damage', amount: 15, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-072',
    name: 'В укрытие',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 2,
    exhaust: true,
    description: 'удвоить защиту',
    tags: ['shield'],
    effects: [{ type: 'block', amount: 5, target: 'player' }],
  },
  {
    id: 'tatiana-card-073',
    name: 'Занять выгодную позицию',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    description: 'следующая карта разыгрывается бесплатно',
    effects: [],
  },
  {
    id: 'tatiana-card-074',
    name: 'Расчетливость',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    description: 'сбрось до 3х карт, возьми столько же',
    effects: [],
  },
  {
    id: 'tatiana-card-075',
    name: 'Патронташ',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    description: 'взять 3 карты',
    effects: [{ type: 'draw', amount: 3 }],
  },
  {
    id: 'tatiana-card-076',
    name: 'Опытный боец',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 0,
    description: 'случайная карта в руке становится бесплатной',
    effects: [],
  },
  {
    id: 'tatiana-card-077',
    name: 'Враги в прицеле',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    description: 'выстрелы накладывают на цель + 1 прицела до конца хода',
    tags: ['aim'],
    effects: [{ type: 'applyStatus', status: 'aim', amount: 1, target: 'enemy' }],
  },
  {
    id: 'tatiana-card-078',
    name: 'Диверсия',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    description: 'враг не может атаковать в этом ходу',
    effects: [],
  },
  {
    id: 'tatiana-card-079',
    name: 'Убийца',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    description: 'после следующей атаки, если у врага будет меньше 10% хп, он умрет',
    effects: [{ type: 'heal', amount: 10 }],
  },
  {
    id: 'tatiana-card-080',
    name: 'Мина',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    description: 'если враг атакует, то все враги получат 12 урона',
    effects: [],
  },
  {
    id: 'tatiana-card-081',
    name: 'Дымовая граната',
    type: 'skill',
    target: 'all-enemies',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    description: 'урон всех врагов уменьшен вдвое на ход',
    effects: [],
  },
  {
    id: 'tatiana-card-082',
    name: 'Блокировщик наблюдения',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    description: 'роботы не видят вас 1 ход, не могут атаковать и накладывать эффекты',
    effects: [],
  },
  {
    id: 'tatiana-card-083',
    name: 'Светошумовая граната',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    description: 'Стан на 1 ход + уязвимость на 1 ход всем',
    tags: ['control'],
    effects: [{ type: 'applyStatus', status: 'vulnerable', amount: 1, target: 'all-enemies' }],
  },
  {
    id: 'tatiana-card-084',
    name: 'Угроза',
    type: 'skill',
    target: 'self',
    rarity: 'rare',
    cost: 1,
    description: '2 слабости + 2 уязвимости (только для живых)',
    tags: ['control'],
    effects: [{ type: 'applyStatus', status: 'weak', amount: 2, target: 'enemy' }, { type: 'applyStatus', status: 'vulnerable', amount: 2, target: 'enemy' }],
  },
];

export const cardLibrary: CardDefinition[] = [...starterCards, ...tatianaRewardCards];

export const getCardById = (cardId: string): CardDefinition => {
  const card = cardLibrary.find((item) => item.id === cardId);

  if (!card) {
    throw new Error(`Card with id "${cardId}" was not found.`);
  }

  return card;
};

export const createStarterDeckCardIds = (): string[] => [
  'basic-shot',
  'basic-shot',
  'basic-shot',
  'raise-shield',
  'raise-shield',
  'raise-shield',
  'reload',
  'roll',
];
